name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for US Artifact Registry
      run: |
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
       docker build \
        --file src/Dockerfile \
        --build-arg DATABASE=${{ secrets.DATABASE }} \
        --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }} \
        -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/liverito:${{ github.sha }} \
        src

    - name: Push to Artifact Registry
      run: |
        docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/liverito:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy liverito \
          --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/liverito:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080