name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: |
        docker build \
          --file src/dockerfile \
          -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/liverito:${{ github.sha }} \
          .

    - name: Push to Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/liverito:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy liverito \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/liverito:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
